### ISSUE TITLE
[Bug] Outline Sometimes Displays for Wrong Document

### ISSUE THREAD

**Issue by SSlinky** [SSlinky/VBA-LanguageServer#13]
**Describe the bug**
Document outline occasionally gets stuck on the wrong document. Can be "fixed" by triggering onDidDocumentChange.  

**Additional context**
May be related to the parsing delay or changing documents while parsing. Unsure. Good luck.

**Comment by SSlinky** [comment]
This doesn't seem to be an issue anymore. Possibly indirectly fixed by the performance improvements. I did manage to get vscode stuck on "no document symbols" when rapidly switching between documents, but I wasn't able to fix it either by triggering onDocumentChange, despite output clearly showing the symbols in the server response. Possible vscode bug.

@sancarn have noticed this in your travels? If not, I think I'll close it.

**Comment by sancarn** [comment]
@SSlinky yeah I think I did experience this but haven't experienced it since you improved performances indeed
