### ISSUE TITLE
[Bug] Parsing broken after functions with arrays as parameters

### ISSUE THREAD

**Issue by sancarn** [SSlinky/VBA-LanguageServer#17]
**Describe the bug**
Initially I noticed this when the Option Explicit error wasn't applicable for `stdCallback` and `stdLambda`.

![image](https://github.com/SSlinky/VBA-LanguageServer/assets/7938900/4df9543a-d2c2-4664-ad82-7817c0799bae)

Now I realise though that the outline doesn't work for these either. So I assume parsing is just broken.

Both these modules have the following declare:

```vb
Private Function stdCallByName(ByRef obj As Object, ByVal funcName As String, ByVal callerType As VbCallType, ByRef args() As Variant) As Variant
  ...
End Function
```

after which it seems parsing breaks

![image](https://github.com/SSlinky/VBA-LanguageServer/assets/7938900/f7e945fe-b24f-48a1-90ff-67fa177909c0)

**To Reproduce**

Minimally you can just load `stdCallback` or `stdLambda` into vscode.

**Comment by sancarn** [comment]
More specifically it seems to break when ByRef is explicitely declared...

![image](https://github.com/SSlinky/VBA-LanguageServer/assets/7938900/14a11730-8d2f-457d-89c3-b56aeb360461)

vs

![image](https://github.com/SSlinky/VBA-LanguageServer/assets/7938900/de8d38e6-5a79-403e-a3d1-42b5927e0ade)

**Comment by SSlinky** [comment]
Thanks for reporting, but also for diving into it. I'll check it out when I get a chance (soon, hopefully).

**Comment by SSlinky** [comment]
This absolutely breaks syntax highlighting but I can't  get it to break the parsing. Will attack this from a textmate grammar perspective.

**Comment by SSlinky** [comment]
Fixed with 28e6fe
