### ISSUE TITLE
[Bug] stdVBA#stdAcc - Parser breaks at FindAll() method?

### ISSUE THREAD

**Issue by sancarn** [SSlinky/VBA-LanguageServer#4]
**Describe the bug**

I opened [stdAcc](https://github.com/sancarn/stdVBA/blob/master/src/stdAcc.cls) with the extension, but outline only populated up to variables of `FindFirst` - not sure why, perhaps something broke the parser?

![image](https://github.com/SSlinky/VBA-LanguageServer/assets/7938900/42f2fffb-4e35-4b43-80bb-202830807166)

The ANTLR log is collossal...

[12-VBA Language Server.log](https://github.com/SSlinky/VBA-LanguageServer/files/15407866/12-VBA.Language.Server.log)

And looks like it might have struggled to rename the file:

![image](https://github.com/SSlinky/VBA-LanguageServer/assets/7938900/4f9849e9-c1d9-48f3-85e6-42fb1bde7774)

**Comment by sancarn** [comment]
Seems like `stdCOM` has no outline at all 😕 

![image](https://github.com/SSlinky/VBA-LanguageServer/assets/7938900/9a25c777-171b-48fa-a48c-3757434785c5)

**Comment by SSlinky** [comment]
It appears you properly broke Antlr near the top by declaring a const in an if block.
![image](https://github.com/SSlinky/VBA-LanguageServer/assets/39886505/03976c70-6211-4de0-b029-1dc079770acc)

On the surface, it should work, but I followed the bouncing ball all the way down to the `SHORTLITERAL` lexer rule which was missing the type hint `^`.

Seems like @Beakerboy's grammar has the same issue.

**Comment by SSlinky** [comment]
The next issue breaking the grammar is a few lines down.

```vb

Private Type TTYPEDESC
    #If Win64 Then
        pTypeDesc As LongLong
    #Else
        pTypeDesc As Long
    #End If
    vt            As Integer
End Type
```

The grammar wasn't written to handle `#If` blocks in random places like this. Recommend you switch to `LongPtr` and simply drop support for < Office 2010 :D

```
typeStmt_Element:
	ambiguousIdentifier (WS? LPAREN (WS? subscripts)? WS? RPAREN)? (
		WS asTypeClause
	)? endOfStatement;
```

**Comment by Beakerboy** [comment]
I have a separate grammer for conditional compilation blocks. I then leverage this grammar In a project called [VBA-Precompiler](https://github.com/Beakerboy/VBA-Precompiler). It’s a python script which will convert a VBA file into a valid precompiled version of the file after you pass your appropriate environment parameters to it.

**Comment by SSlinky** [comment]
Fixed the type issue in 1075c15. Next issue is still `#If` blocks...

**Comment by SSlinky** [comment]
@Beakerboy good idea - I do have a TODO to break the grammar down into smaller chunks so that I can more efficiently parse sections of code. Having it precompile also makes sense, but sounds like there's hidden gotchas in some things. For example, it might be tempting to take the first section of the if block and whitespace everything else out so that it's nice to the grammar, but that would hide an issue.

```vb
Type Foo
    #If Win64 Then
        Bar As LongLong
    #Else
        Baz As Long
    #End If
End Type
```

**Comment by Beakerboy** [comment]
The conditional compilation is a tricky situation. ANTLR requires nested scopes, like in html:

```
<p>
    <table>
    </table>
</p>
```

However, since precomilation is almost a meta-language built on top of VBA, you are allowed to do stuff like:

```
<p>
    <#a>
    <table>
    </#a>
    <#a>
    <table>
    </#a>
    </table>
</p>
```

And this causes the ANTLR grammar to have no idea how to handle the duplicated table tags. In VBA, obviously the table is actually a function declaration, or a for loop or something, but the scope issue is the same.

**Comment by SSlinky** [comment]
I was looking [here](https://github.com/antlr/grammars-v4/blob/master/vba/vba.g4#L453) and I can see caret is handled on an identifier but it doesn't seem to be on a literal, e.g., `0^`.

**Comment by Beakerboy** [comment]
You’re looking at the vba6 grammar that has a lot of bugs.
Try this:
https://github.com/Beakerboy/grammars-v4/tree/coverage/vba

**Comment by sancarn** [comment]
> Recommend you switch to `LongPtr` and simply drop support for < Office 2010 :D

😂

Makes sense that these break the grammar though. Very difficult to handle this in a grammar unless you do what beakerboy did and precompile code beforehand I suppose.

**Comment by SSlinky** [comment]
```vb
#If VBA7 Then
  Public Property Get Pointer() As LongPtr
#Else
  Public Property Get Pointer() As Long
#End If
End Property
```

@sancarn, you are a monster and I don't know how you sleep at night.

**Comment by sancarn** [comment]
That's actually a critical one in terms of compatibility 😂 If you use the redefinition trick e.g.

```vb
#If VBA7 = 0 then
  Enum LongPtr
    [_]
  End Enum
#End if
```

You get loads of conflicts with other modules 😢 So gotta actually use compiler in these instances to remain compatible.

**Comment by SSlinky** [comment]
FYI this was breaking the grammar because your arguments are assigned a default without a space between the operator, e.g., `Optional ByVal foo As String="bar")`. It's not technically legal VBA but I've updated the grammar to allow it since the editor would add those spaces in anyway.

**Comment by SSlinky** [comment]
You may want to import into Excel and just immediately export. Will fix a lot of those issues. I've published another patch which will address a few things.

**Comment by sancarn** [comment]
> The grammar is a ground up build, so not at all similar. The new package had breaking changes. So basically everything was broken. I'm getting there, but it's half two in the morning again.

Are you generating the parsers from the antlr grammar directly? Or are you building the grammar manually? If manually, tree-sitter might be advantageous given it outputs ultra-fast binary parsers.

**Comment by SSlinky** [comment]
Fair enough. And yeah, I'm generating the parser from the grammar so I'd prefer not to make any customisations to that or they'll be lost every time I generate the TS.

Frustratingly, the newer generator, antlr4ng, doesn't seem to generate classes that have a `.text` property and the `.toString()` is trying to be too clever. It prints the underlying text for nodes, but everything else is a "tree" which is why you see those numbers in the screen shot.

**Comment by SSlinky** [comment]
`getText()`!

I found it in the layers of implements and extends! Just need to rebuild out the things I already had with the new grammar.

**Comment by SSlinky** [comment]
@Beakerboy if you'd like to enable issues on your repo, I can raise them as I find them. I've had to fix a couple of things and I'm sure I'll find more.

* classAttr missing attribute VB_DESCRIPTION.
* `On Error GoTo -1` not supported.

**Comment by Beakerboy** [comment]
What does `GOTO -1` actually mean? How is it different than 0?

**Comment by sancarn** [comment]
`On Error GoTo -1` is functionally equivalent to `Err.Clear`

**Comment by Beakerboy** [comment]
Issues are now on. I guess the best course of action is to allow this in the grammar, and then have the linter flag it as a non-conformance. I’ll reach out to Microsoft to see what they say.

**Comment by SSlinky** [comment]
> `On Error GoTo -1` is functionally equivalent to `Err.Clear`.
> 
> See [stackoverflow](https://stackoverflow.com/a/30994055/6302131).
> 
> Or even [here](https://bettersolutions.com/vba/error-handling/on-error-goto-1.htm):
> 
> > This statement resets the [Err Object](https://bettersolutions.com/vba/error-handling/err-object.htm) AND resets/clears the VBA Error memory.

It's not really the same. `Err.Clear` just clears the error. If you've already caught an error, you won't be able to catch something else and you won't be able to set a new catcher.

It's functionally equivalent to

```
On Error GoTo 0
On Error GoTo TheSameLabelWeSetBefore
```

**Comment by sancarn** [comment]
> It's functionally equivalent to
> 
> ```
> On Error GoTo 0
> On Error GoTo TheSameLabelWeSetBefore
> ```

Oh ok, fair enough :)

**Comment by SSlinky** [comment]
@sancarn

> I don't personally see there's much wrong with it...

`Public Function CreateFromApplication(Optional ByVal oApp as Object = Nothing, more As Arg, arg As Long) As stdAcc`

*narrows eyes

Just spent a while debugging this because it breaks all method declarations! I've actually updated grammar to be a little more tolerant of people who whish to list their args out of order because for this use case, the parser shouldn't be blowing up all the time, so should be as generic as possible.

Starting to look respectable again. About time for a PR, methinks.

![image](https://github.com/SSlinky/VBA-LanguageServer/assets/39886505/300d3510-5a0f-4c98-8c55-db332ce778f1)

**Comment by SSlinky** [comment]
Safe to say that the original issue is now fixed.

**Comment by sancarn** [comment]
> Just spent a while debugging this because it breaks all method declarations

Oh in what way?

**Comment by SSlinky** [comment]
You can't have optional args before positional ones. I'm not sure why it so catastrophically breaks parsing, but 🤷 it works any which way now. I'll write some diagnostics to send to VSCode to highlight the issue though.

**Comment by sancarn** [comment]
Oh for a minute I actually thought that was code in my class 🤣 I figured that was an issue while looking at it. But the declare in the module is:

> `Public Function CreateFromApplication(Optional ByVal oApp as Object = Nothing) As stdAcc`

So not sure where you got those args from :P Anyhow good it doesn't break the whole parser now!

**Comment by SSlinky** [comment]
Oh, I may have done that, haha.

Please! This is supposed to be a _happy_ occasion! Let's not bicker and argue about "who killed which parser".

![image](https://github.com/SSlinky/VBA-LanguageServer/assets/39886505/3f1f10f8-f173-4332-b2a0-d3d56b70b71e)
